### ISSUE TITLE
Add support for building raw disk images in UI

### ISSUE THREAD

**Issue by frelon** [rancher/elemental-ui#143]
When https://github.com/rancher/elemental-operator/pull/557 is merged it will be possible to build raw disk images using the SeedImage resource.

We would like to be able to build raw images from the UI in the same way as for ISOs.

The API is the same, but we include the Type-field on the SeedImage resource:

```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: fire-img
  namespace: fleet-default
spec:
  type: raw
  baseImage: registry.suse.com/rancher/elemental-teal/5.4:1.2.2
  registrationRef:
    apiVersion: elemental.cattle.io/v1beta1
    kind: MachineRegistration
    name: fire-nodes
    namespace: fleet-default
```
