### ISSUE TITLE
Wrong default cloud config file with standard user

### ISSUE THREAD

**Issue by juadk** [rancher/elemental-ui#175]
## Description
Standard user with elemental admin role does not see the expected default cloud-config file:
```
config:
  cloud-config:
    users:
    - name: root
      passwd: root
  elemental:
    install:
      poweroff: true
      device: /dev/nvme0n1
```
instead of:
```
config:
  cloud-config:
    users:
    - name: root
      passwd: root
  elemental:
    install:
      reboot: true
      device-selector:
      - key: Name
        operator: In
        values:
        - /dev/sda
        - /dev/vda
        - /dev/nvme0
      - key: Size
        operator: Gt
        values:
        - 25Gi
      snapshotter:
        type: btrfs
```

There is no issue if you use the admin account.
Probably introduced by https://github.com/rancher/elemental-ui/pull/169

## Env
Rancher: `2.8.3`
Elemental dev UI: `1.3.1-rc4`
Elemental operator: `1.6.0`
