### ISSUE TITLE
SeedImage add platform selector

### ISSUE THREAD

**Issue by frelon** [rancher/elemental-ui#181]
When building installation media, it's also possible to select the target platform of the built image/iso.

Right now it could be a hardcoded list with `linux/x86_64` and `linux/arm64` and default to the current platform rancher is running on (or x86 if easier).

This should set the `targetPlatform` field on the seedImage resource:

```
apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: fire-img
  namespace: fleet-default
spec:
  baseImage: registry.opensuse.org/isv/rancher/elemental/dev/containers/suse/sl-micro/6.0/baremetal-os-container:latest
  targetPlatform: linux/arm64
```
