### ISSUE TITLE
Download SeedImage's checksum

### ISSUE THREAD

**Issue by anmazzotti** [rancher/elemental-ui#221]
SURE-8889

Part of https://github.com/rancher/elemental-operator/issues/823

`SeedImage.status.checksumURL` has been added (gate to `elemental-operator` >= `v1.6.5` ) to provide a checksum of the built image artifact.

It does follow the same rule as `downloadURL`, so the `SeedImage` Ready condition has to be true for this field to be usable.  

```yaml
status:
  checksumURL: https://172.18.0.2.sslip.io/elemental/seedimage/wr9xntd96nj6c6rztcfcsfnbtgb7xpz47fxb9dhp4mkjj27cttmxkf/fire-nodes-2024-08-22T07:48:10Z.iso.sha256
  downloadURL: https://172.18.0.2.sslip.io/elemental/seedimage/wr9xntd96nj6c6rztcfcsfnbtgb7xpz47fxb9dhp4mkjj27cttmxkf/fire-nodes-2024-08-22T07:48:10Z.iso
```

The request is to be able to download this checksum from the UI as well, as it is for the image artifact.
