### ISSUE TITLE
Missing schema validation when loading registration config from file.

### ISSUE THREAD

**Issue by anmazzotti** [rancher/elemental-ui#226]
This is related to: https://github.com/rancher/elemental-operator/issues/869

I created this (incorrect) config file: 

```yaml
config:
  #cloud-config:
  users:
  - name: root
    passwd: root
```

And used the "Read from file" button on the UI when creating a new MachineRegistration. Despite the schema being invalid, the UI did not error out and still proceeded creating the registration with an empty config.

Would it be possible to validate the schema and error out instead? 
In this case it would fail as `MachineRegistration.spec.config.users` does not exist.
