### ISSUE TITLE
Display image creation date

### ISSUE THREAD

**Issue by anmazzotti** [rancher/elemental-ui#240]
Starting from elemental-operator `1.7.2`, the ManagedOSVersion will have a new metadata `created` timestamp.
This is in [Unix time format](https://en.wikipedia.org/wiki/Unix_time). For example:

```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersion
metadata:
  name: baremetal-v2.2.0-3.9-os
  namespace: fleet-default
spec:
  metadata:
    created: 1732636343
    displayName: SL Micro Baremetal 6.1 OS
    platforms:
      - linux/x86_64
      - linux/aarch64
    upgradeImage: registry.suse.com/suse/sl-micro/6.1/baremetal-os-container:2.2.0-3.9
  type: container
  version: v2.2.0-3.9
```

It would be nice if we can somehow display this timestamp in a human readable format when listing the ManagedOSVersions.
Would also be nice to do a conversion based on the browser's timezone. In any case I think it should be best to explicitly display the used timezone.
